### ISSUE TITLE
Alldebrid doesn't show up on movie/show page

### ISSUE THREAD

**Issue by jinstan101** [MrMonkey42/stremio-addon-debrid-search#12]
![image](https://github.com/MrMonkey42/stremio-addon-debrid-search/assets/139099774/bbe383a7-8eea-4916-b458-8d8e76b0faf7)
![image](https://github.com/MrMonkey42/stremio-addon-debrid-search/assets/139099774/fdd6c7be-e6af-4c09-9fac-b4ae58d95efc)

As the title suggest.
also please add host downloads on alldebrid as well, not just real-debrid.
thanks for making this addon possible.

**Comment by MrMonkey42** [comment]
Related to https://github.com/MrMonkey42/stremio-addon-debrid-search/issues/9

**Comment by jinstan101** [comment]
> Related to #9

Doesn't work with alldebrid. Only Rd.

**Comment by asaddon** [comment]
@MrMonkey42 Any updates/fix for this issue?

**Comment by sbvkrishna** [comment]
AllDebrid has a limitation to work in Stremio addons ([More info here](https://github.com/mhdzumair/MediaFusion/issues/58). But someone who has AllDebrid informed me that AllDebrid is now working fine in Stremio addons

**Comment by MrMonkey42** [comment]
@asaddon @jinstan101 Is AllDebrid still not working in Stremio addons like DebridSearch?

**Comment by asaddon** [comment]
> @asaddon @jinstan101 Is AllDebrid still not working in Stremio addons like DebridSearch?

It works on the home page like Torentio addon but results are not shown on the video/movie pages.

**Comment by MrMonkey42** [comment]
@asaddon Someone on Discord informed me that AllDebrid started working for them in movie/series pages (i.e., streams). But I cannot verify it personally as I don't have AllDebrid

**Comment by oathzed** [comment]
> @asaddon Someone on Discord informed me that AllDebrid started working for them in movie/series pages (i.e., streams). But I cannot verify it personally as I don't have AllDebrid

Hey Man, its no longer working for AllDebrid again :(
