### ISSUE TITLE
Addon didnt work for me :( 

### ISSUE THREAD

**Issue by razeNFR** [MrMonkey42/stremio-addon-debrid-search#19]
Hello,

I tried many times your addons, because im french and so much contents are not in my language, so your addons is game changer for me, i have installed Torrentio + Torrentio Catalogs based on Alldebrid, your Addons with my ApiKey too, and when i search for a movie or series, that i have added torrents in my alldebrid catalogs before, i didnt see the result of Debrid Search, only torrentio, and torrent that i have cached before are not here....

You know why ?

Thank you.

**Comment by MrMonkey42** [comment]
Matching might be working due to foreign language name in the torrents you added to your Debrid account

**Comment by flo1043** [comment]
Have you tried with realdebrid? However, I have the same concerns for my parents. My RD account reports all the information from the Debrid Search application whether on my parents' STREMIO account or mine, but their RD account does not report any information with Debrid Search whether on their STREMIO account or mine with the same files. Thanks to this application, we unlock good quality French links (mainly series). Thank you for your wonderful work MrMonkey42.
