### ISSUE TITLE
Quite a few users on Reddit reporting version 0.1.8 not working

### ISSUE THREAD

**Issue by bequbed** [MrMonkey42/stremio-addon-debrid-search#20]
https://www.reddit.com/r/StremioAddons/s/cTp1DO8QtK

As per the Reddit post and my own experience, version 0.1.8 all of a sudden has stopped working.

Version 0.1.5 seems to be mostly working with movies however some TV shows won't show any results.

**Comment by MrMonkey42** [comment]
Is it still not working?

**Comment by MrMonkey42** [comment]
I have verified it again and addon 0.1.8 is working fine with both RD and DL

**Comment by MrMonkey42** [comment]
Resolving due to inactivity
