### ISSUE TITLE
Refresh Sources on Stremio

### ISSUE THREAD

**Issue by Pentonize** [MrMonkey42/stremio-addon-debrid-search#21]
So I use Debrid Search as a bit of a back up and a good way to add manual sources to stremio

But when I add my torrent to real debrid, the stremio addon (Debrid Search) won't search again if I already attempted to search.

Does this addon refresh periodically or does it do 1 search once, then never searches again?

**Comment by MrMonkey42** [comment]
This is probably due to the local cache. Will fix it shortly

**Comment by MrMonkey42** [comment]
I have deployed a small change to the cache configuration. Will have to check if this would fix the stale cache or not

**Comment by MrMonkey42** [comment]
Looks like the cache configuration is still having 4hr validity, enough though I kept it as 1min. I guess Stremio deployment service (beamup) is setting the cache validity to be 4hrs :/

**Comment by MrMonkey42** [comment]
Issue is resolved

**Comment by MrMonkey42** [comment]
Amy results fetched would stay cached for 1minute and then get refreshed

**Comment by Pentonize** [comment]
Excellent thank you so much!!!!
