### ISSUE TITLE
Does the add-on show new files instantly after adding them to my RD downloads or torrents?

### ISSUE THREAD

**Issue by Samshinegithub** [MrMonkey42/stremio-addon-debrid-search#28]
I just added a movie file to RD
DEBRID search addon isn't showing the file or even loads the addon when I opened the movie in STREMIO ( I tried this 5  minutes after adding the file to my RD downloads)

I unrestricted a gdrive file to my links in RD

**Doesn't it show new files instantly**?
Need help Sir

Edit:It **now shows all the files after 8 hours** , 
(I just woke up)

**Sir , exactly how many hours does it take for a 
movie/show to show up in DEBRID SEARCH addon after adding it in MY REAL DEBRID account?**

**Comment by MrMonkey42** [comment]
The catalog in home page or discover page refreshes after 4hrs I think. But stream links in movie/show details page will refresh within around 1 minute
