### ISSUE TITLE
Debrid Search streams from a different IP

### ISSUE THREAD

**Issue by znre** [MrMonkey42/stremio-addon-debrid-search#29]
Is this intended? This is a screenshot of RD's download page and I found that Debrid search uses a different IP.

![image](https://github.com/MrMonkey42/stremio-addon-debrid-search/assets/70197545/fe931362-b36e-4c3c-9ea0-78e60339ffb1)

**Comment by MrMonkey42** [comment]
Download links are fetched by the addon server (hosted on official stremio hosting server) using RealDebrid API and sent to the client device which actually streams the content. It could be possible that API usage might be getting logged under different IP

**Comment by MrMonkey42** [comment]
Once check if downloads are still getting logged under addon's IP address instead of enduser's IP address
