### ISSUE TITLE
Please add option to remove catalog from home screen

### ISSUE THREAD

**Issue by Nowhereman04** [MrMonkey42/stremio-addon-debrid-search#35]
Hello, Great add-on!
It would be amazing if there was an option to hide the catalog from the home screen.

Thanks

**Comment by MrMonkey42** [comment]
Going forward, catalog would no longer show up in home screen but can be enabled as per your preference.

https://github.com/MrMonkey42/stremio-addon-debrid-search/commit/bdd2ccd8db503a56ae4f74e30d4c4d15d59150d0
