### ISSUE TITLE
addon isn't working

### ISSUE THREAD

**Issue by bingoxo** [MrMonkey42/stremio-addon-debrid-search#37]
i get Playback error , please try again 

please look into it and thanks in advance

**Comment by johnnyw94** [comment]
Yes same herr

**Comment by UselessUniform** [comment]
Same error here too, for a few days

**Comment by Kwaice** [comment]
Yeah same, not working since a few days ("Playback error")

**Comment by MalcolmBrt** [comment]
Same error, i am using real-debrid

**Comment by MattFaz** [comment]
+1, not working for me on iOS or Sony TV

**Comment by directoux** [comment]
Whenever i try to play a video through the library via the debrid search add on it get an error that says 'Mediaplayer error code - 1extra 0' on my Amazon Firestick
On my computer running Linux Mint with the flatpak version of Stremio I don't get an error but no video starts to play even if i leave it trying for over 5 mins.

**Comment by anymeofu** [comment]
Not working for me too on stremio android app

**Comment by equinox** [comment]
@MrMonkey42 Any chance you could take a look at this please?

**Comment by tikkamasalla** [comment]
yeah, I really loved this addon, stremio is practically unusable without this.

**Comment by MrMonkey42** [comment]
Taking a look. Is this issue impacting only RealDebrid users?

**Comment by bingoxo** [comment]
> Taking a look. Is this issue impacting only RealDebrid users?

The issue is with RD , don't have AD or PM to test unfortunately

**Comment by directoux** [comment]
> Taking a look. Is this issue impacting only RealDebrid users?

I only have real debrid, and so cannot say if other debrid services are working with your add on

**Comment by jaytee67** [comment]
Same thing with me. I'm using Real Debrid. Not working on Mac, 2 different LG Smart tvs and 2 different Chromecasts. Cant say for other debrid providers.

**Comment by wenchiee** [comment]
> Taking a look. Is this issue impacting only RealDebrid users?

Debrid Link work fine, Real Debrid only DDLs work when going through the title, but in Discover torrents work. 
Since you're taking a look, would it be possible to have Debrid Link DDLs work through the title like they do with Real Debrid please?

**Comment by who-is-matt** [comment]
I've also been having this problem for the last few weeks, also using Real-Debrid.  Links in the dedicated Debrid Search catalog and in the Discovery panel work, but source links provided by Debrid Search in regular source lists throw ERROR_CODE_IO_BAD_HTTP_STATUS (in Stremio for Android TV).

**Comment by MrMonkey42** [comment]
I have renewed my RD account to test this and it seems to be working fine for me without any issue. Can anyone else confirm?

**Comment by MalcolmBrt** [comment]
I get this error while trying to play a movie in my library

![Screenshot_20241120-090232](https://github.com/user-attachments/assets/1fe46fb9-301d-4ec6-9f54-bbf0d002d85f)

**Comment by wenchiee** [comment]
> I have renewed my RD account to test this and it seems to be working fine for me without any issue. Can anyone else confirm?
> 
> Edit: To be specific, I have tested both Stremio mobile app and TV version to play the content downloaded under https://real-debrid.com/torrents in my RD account. Is this where the issue is?

Thanks, just tested again. Playing the torrents from RD account via 'Discover' has been fixed since about the time Torrentio came back online. However, playing them when going through the poster (like all other add-ons) is still returning 'ERROR_CODE_IO_BAD_HTTP_STATUS' on Android TV, 'Stremio encountered an error with this media' on android mobile and 'Playback error, please try Again' on PC.

**Comment by tikkamasalla** [comment]
> I have renewed my RD account to test this and it seems to be working fine for me without any issue. Can anyone else confirm?
> 
> Edit: To be specific, I have tested both Stremio mobile app and TV version to play the content downloaded under https://real-debrid.com/torrents in my RD account. Is this where the issue is?

No, you can play from your downloads even without this addon, the feature we all use that is currently broken, is playing downloaded items from the actual movie/tv show page or from the search.

**Comment by jaytee67** [comment]
I just added a fresh magnet link to demonstrate what i am experiencing. Accessing via downloads works as seen below <img width="1129" alt="1" src="https://github.com/user-attachments/assets/34b1a9b9-d19f-4fcb-b324-d4cba4a31c38">

However, when viewing from gallery i get this message. 
<img width="1110" alt="2" src="https://github.com/user-attachments/assets/a89b314d-54c5-4683-8c53-50d70a5f0a61">

(Demonstration only)

**Comment by MrMonkey42** [comment]
> > I have renewed my RD account to test this and it seems to be working fine for me without any issue. Can anyone else confirm?
> > Edit: To be specific, I have tested both Stremio mobile app and TV version to play the content downloaded under https://real-debrid.com/torrents in my RD account. Is this where the issue is?
> 
> No, you can play from your downloads even without this addon, the feature we all use that is currently broken, is playing downloaded items from the actual movie/tv show page or from the search.

I tested playing the movie from movie page only, not via discover or catalog on home page. The movie was manually added into RD account using magnet link

**Comment by johnnyw94** [comment]
> > > I have renewed my RD account to test this and it seems to be working fine for me without any issue. Can anyone else confirm?
> > > Edit: To be specific, I have tested both Stremio mobile app and TV version to play the content downloaded under https://real-debrid.com/torrents in my RD account. Is this where the issue is?
> > 
> > No, you can play from your downloads even without this addon, the feature we all use that is currently broken, is playing downloaded items from the actual movie/tv show page or from the search.
> 
> I tested playing the movie from movie page only, not via discover or catalog on home page. The movie was manually added into RD account using magnet link

Try this, go to a random movie, 

Click any RD+ link, play it and stop after a few seconds, now it's added in the RD library right. 

Now close the app and remove it from recents. 

Open the app again, and go to that same movie page, now DebridSearch will show that movie link in add-on results right.

Now click that one, it'll show the playback error.

**Comment by MrMonkey42** [comment]
> Try this, go to a random movie,
> 
> Click any RD+ link, play it and stop after a few seconds, now it's added in the RD library right.
> 
> Now close the app and remove it from recents, clear cache.
> 
> Open the app again, and go to that same movie page, now DebridSearch will show that movie link in add-on results right.
> 
> Now click that one, it'll show the playback error.

Thanks, let me try this today and get back

**Comment by johnnyw94** [comment]
> 
> > Try this, go to a random movie,
> > 
> > Click any RD+ link, play it and stop after a few seconds, now it's added in the RD library right.
> > 
> > Now close the app and remove it from recents, clear cache.
> > 
> > Open the app again, and go to that same movie page, now DebridSearch will show that movie link in add-on results right.
> > 
> > Now click that one, it'll show the playback error.
> 
> Thanks, let me try this today and get back

Yeah thank you!

**Comment by jaytee67** [comment]
Appreciate you guys for looking into this genuinely 🙏🏽

**Comment by MrMonkey42** [comment]
> > Try this, go to a random movie,
> > Click any RD+ link, play it and stop after a few seconds, now it's added in the RD library right.
> > Now close the app and remove it from recents, clear cache.
> > Open the app again, and go to that same movie page, now DebridSearch will show that movie link in add-on results right.
> > Now click that one, it'll show the playback error.
> 
> Thanks, let me try this today and get back

I'm able to reproduce the issue now by following above steps. To resolve the streaming link for the selected video, looks like RD has made passing user's IP address as mandatory. Here's the error being returned by RD - `{ip} is missing, please provide enduser IP address`. Will work on the fix

**Comment by johnnyw94** [comment]
> > > Try this, go to a random movie,
> > > Click any RD+ link, play it and stop after a few seconds, now it's added in the RD library right.
> > > Now close the app and remove it from recents, clear cache.
> > > Open the app again, and go to that same movie page, now DebridSearch will show that movie link in add-on results right.
> > > Now click that one, it'll show the playback error.
> > 
> > Thanks, let me try this today and get back
> 
> I'm able to reproduce the issue now by following above steps. To resolve the streaming link for the selected video, looks like RD has made passing user's IP address as mandatory. Here's the error being returned by RD - `{ip} is missing, please provide enduser IP address`. Will work on the fix

Thank you so much!

**Comment by DevonCM** [comment]
> Taking a look. Is this issue impacting only RealDebrid users?

AllDebrid isn't working either, but it's not even showing results like RD was.  Really hope this can be addressed, with everything that's going on with this stuff now.

**Comment by MrMonkey42** [comment]
Update: I have deployed the fix earlier today  (https://github.com/MrMonkey42/stremio-addon-debrid-search/commit/79595e956f6fc7a3dce434c95cba0abaf38a3347), yet the issue doesn't seem to be resolved. Have opened a ticket with RD support to sort this out

**Comment by recital-cpu** [comment]
> Update: I have deployed the fix earlier today ([79595e9](https://github.com/MrMonkey42/stremio-addon-debrid-search/commit/79595e956f6fc7a3dce434c95cba0abaf38a3347)), yet the issue doesn't seem to be resolved. Have opened a ticket with RD support to sort this out

Thanks for efforts

**Comment by MrMonkey42** [comment]
Update: This issue should be resolved now with the [updated fix](https://github.com/MrMonkey42/stremio-addon-debrid-search/commit/19ed519871c9f6acf97ae53180259c8e1fe1d575). Do let me know if anyone is still having any issues

**Comment by recital-cpu** [comment]
> Update: This issue should be resolved now with the [updated fix](https://github.com/MrMonkey42/stremio-addon-debrid-search/commit/19ed519871c9f6acf97ae53180259c8e1fe1d575). Do let me know if anyone is still having any issues

just cheked its fixed now thank you so much

**Comment by johnnyw94** [comment]
Damn thank you so much! ✨🔥
