### ISSUE TITLE
Video not supported

### ISSUE THREAD

**Issue by MissingNerd** [MrMonkey42/stremio-addon-debrid-search#38]
I was trying to get an episode for a show in a standard mp4 format from RD in Stremio Web. Episode shows up, can be selecten in Stremio but the player says "Video not supported". When trying to play the episode in VLC via a m3u file I get the following errors:

access error: HTTP 500 error
http error: local stream 1 error: Cancellation (0x8)

**Comment by tikkamasalla** [comment]
[addon is not active right now, check ](https://github.com/MrMonkey42/stremio-addon-debrid-search/issues/37)

**Comment by MrMonkey42** [comment]
Tracking this issue in https://github.com/MrMonkey42/stremio-addon-debrid-search/issues/37
