### ISSUE TITLE
TorBox support request

### ISSUE THREAD

**Issue by vladskz** [MrMonkey42/stremio-addon-debrid-search#41]
Becooming more popular, can this addon also get TorBox supprt?

**Comment by Gators25** [comment]
That would be cool

**Comment by MrMonkey42** [comment]
Will signup for TorBox later today and start working on this

**Comment by Gators25** [comment]
Sweet!

**Comment by bingoxo** [comment]
> Will signup for TorBox later today and start working on this
> 
> API at https://api-docs.torbox.app/

@wamy-dev , hook our man up here please

**Comment by MrMonkey42** [comment]
> Sure, open up a ticket @MrMonkey42, just make sure you say what addon you are a part of and we will get you sorted out.

@Wamy-Dev  I tried to sign up but looks like new signups are blocked temporarily. Any way to work around this?

**Comment by Wamy-Dev** [comment]
Open a ticket @MrMonkey42

**Comment by MrMonkey42** [comment]
> Open a ticket @MrMonkey42

I think I cannot open a ticket without having an account. Let me message you on discord directly to sort this out

**Comment by MrMonkey42** [comment]
TorBox support for torrent downloads has been added in v0.1.11. Support for web hoster downloads and usenet downloads will be coming next updates.

**Comment by oathzed** [comment]
> TorBox support for torrent downloads has been added in v0.1.11. Support for web hoster downloads and usenet downloads will be coming in next updates.

Awesome... Looking forward to trying it out

**Comment by MrMonkey42** [comment]
Closing this, will create separate thread for the missing features
